# Generated by Django 3.2.7 on 2022-11-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_postcomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomments',
            name='commented_on',
        ),
    ]
