# Generated by Django 3.2.7 on 2022-11-07 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_remove_postcomments_commented_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='commented_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
